import datetime


TO_NUMBER = lambda n: float(n)


def TO_DATE(s):
    # Check number of hypens to understand formatting: 0 >> just year, 1 >> year-month, 2 >> year-month-day
    if s.count("-") == 2:
        return datetime.datetime.strptime(s, "%Y-%m-%d")
    if s.count("-") == 1:
        return datetime.datetime.strptime(s, "%Y-%m")
    if s.count("-") == 0:
        return datetime.datetime.strptime(s, "%Y")


def asset_schema():
    """
    Return validation schema for ASSETS data type.
    """
    schema = {
        "AA1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "max": datetime.datetime(2030, 12, 31, 0, 0),
            "meta": {"label": "Pool Cut-off Date"},
        },
        "AA2": {"type": "string", "meta": {"label": "Pool Identifier"}},
        "AA3": {"type": "string", "meta": {"label": "Servicer Name"}},
        "AA4": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Backup Servicer Name"},
        },
        "AA5": {"type": "string", "meta": {"label": "Loan or Lease Identifier"}},
        "AA6": {"type": "string", "nullable": True, "meta": {"label": "Originator"}},
        "AA7": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Regulated Loan"},
        },
        "AA8": {
            "type": "string",
            "meta": {"label": "Borrower Identifier"},
        },
        "AA9": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Group Company Identifier"},
        },
        "AA10": {
            "type": "string",
            "meta": {"label": "Loan or Lease Currency Denomination "},
        },
        "AA15": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Borrower Credit Quality"},
        },
        "AA16": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "nullable": True,
            "meta": {"label": "Borrower's Employment Status"},
        },
        "AA17": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Primary Income"},
        },
        "AA18": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Primary Income Currency"},
        },
        "AA19": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Amortisation Type"},
        },
        "AA20": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Income Verification for Primary Income"},
        },
        "AA21": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Geographic Region"},
        },
        "AA22": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "max": datetime.datetime.now(),
            "meta": {"label": "Originator Date"},
        },
        "AA23": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "min": datetime.datetime(2012, 1, 1),
            "meta": {"label": "Expected Loan or Lease Maturity"},
        },
        "AA24": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Original Loan or Lease Term"},
        },
        "AA25": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "max": datetime.datetime.now(),
            "meta": {"label": "Pool Addition Date"},
        },
        "AA26": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Original Principal Balance"},
        },
        "AA27": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Principal Outstanding Balance"},
        },
        "AA28": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Scheduled Payment Due"},
        },
        "AA29": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Scheduled Payment Frequency"},
        },
        "AA30": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Revenue"},
        },
        "AA31": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "EBITDA"},
        },
        "AA32": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "max": datetime.datetime.now(),
            "meta": {"label": "Date of the Financial Statements at Underwriting"},
        },
        "AA33": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Financial Statement Currency"},
        },
        "AA34": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Down Payment Amount"},
        },
        "AA35": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Loan to Value"},
        },
        "AA36": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "nullable": True,
            "meta": {"label": "Product Type"},
        },
        "AA37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Option to Buy Price"},
        },
        "AA39": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Rate Reset Interval"},
        },
        "AA40": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Interest or Discount Rate"},
        },
        "AA41": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
            ],
            "nullable": True,
            "meta": {"label": "Current Interest Rate Basis"},
        },
        "AA42": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Interest Rate Margin"},
        },
        "AA43": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Discount Rate"},
        },
        "AA44": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Car Manufacturer"},
        },
        "AA45": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Car Model"},
        },
        "AA46": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Engine Size"},
        },
        "AA47": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Year of Registration"},
        },
        "AA48": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "New or Used Car"},
        },
        "AA49": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Car Valuation at Loan or Lease Origination"},
        },
        "AA50": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Residual Value of Vehicle"},
        },
        "AA51": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Securitised Residual Value"},
        },
        "AA52": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Updated Residual Value of Vehicle"},
        },
        "AA53": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Updated Residual Valuation of Vehicle"},
        },
        "AA54": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Origination Channel"},
        },
        "AA55": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Customer Type"},
        },
        "AA56": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Loan or Lease Ever in Arrears"},
        },
        "AA57": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Payment Method"},
        },
        "AA58": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Removed from the Pool"},
        },
        "AA59": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Deposit Amount"},
        },
        "AA60": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Cap Rate"},
        },
        "AA61": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Floor Rate"},
        },
        "AA65": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears Balance"},
        },
        "AA66": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Number of Months in Arrears"},
        },
        "AA67": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Default Date"},
        },
        "AA68": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Gross Default Amount"},
        },
        "AA69": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Sale Price"},
        },
        "AA70": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "meta": {"label": "Loss on Sale"},
        },
        "AA71": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries"},
        },
        "AA72": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Redemption Date"},
        },
        "AA73": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Residual Value Losses"},
        },
        "AA74": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
            "nullable": True,
            "meta": {"label": "Account Status"},
        },
    }

    return schema


def bond_info_schema():
    """
    Return validation schema for BOND_INFO data type.
    """
    schema = {
        "BAA1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Report Date"},
        },
        "BAA2": {"type": "string", "meta": {"label": "Issuer"}},
        "BAA4": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "All Reserve Accounts at Target Balance"},
        },
        "BAA5": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Drawings under Liquidity Facility"},
        },
        "BAA11": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread Amount"},
        },
        "BAA12": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Trigger Measurements/Ratios"},
        },
        "BAA13": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Annualised Constant Pre-payment Rate"},
        },
        "BAA14": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread %"},
        },
        "BAA15": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Receivables Sold to SPV"},
        },
        "BAA16": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Gross Defaults – Pool"},
        },
        "BAA17": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries - Pool"},
        },
        "BAA18": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Revolving Period End Date"},
        },
        "BAA19": {"type": "string", "meta": {"label": "Point Contact"}},
        "BAA20": {"type": "string", "meta": {"label": "Contact Information"}},
        "BAA25": {"type": "string", "meta": {"label": "Bond Class Name"}},
        "BAA26": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "International Securities Identification Number"},
        },
        "BAA27": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Payment Date"},
        },
        "BAA28": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Principal Payment Date"},
        },
        "BAA29": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Bond Currency"},
        },
        "BAA30": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BAA31": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Ending Balance Subsequent to Payment"},
        },
        "BAA32": {
            "type": "string",
            "allowed": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
            ],
            "nullable": True,
            "meta": {"label": "Reference Rate"},
        },
        "BAA33": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Relevant Margin"},
        },
        "BAA34": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "meta": {"label": "Coupon Reference Rate"},
        },
        "BAA35": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "meta": {"label": "Current Coupon"},
        },
        "BAA36": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Interest Shortfall "},
        },
        "BAA37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Principal Shortfalls"},
        },
        "BAA38": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "meta": {"label": "Legal Maturity"},
        },
        "BAA39": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Bond Issue Date"},
        },
        "BAA40": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Scheduled Maturity Date"},
        },
        "BAA41": {
            "type": "string",
            "allowed": ["0", "1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Interest Payment Frequency"},
        },
        "BAA42": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Step-Up Date"},
        },
        "BAA43": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Step-Up Rate"},
        },
        "BAA44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Initial Credit Enhancement in percentage terms"},
        },
        "BAA45": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Credit Enhancement in percentage terms"},
        },
        "BAA46": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "FX Swap Rate"},
        },
    }

    return schema
